version: "3"

services: 
  postgres:
    image: postgres
    network_mode: "host"
    ports: 
      - "5432:5432"
    volumes: 
      - /app/data/postgres/:/var/lib/postgresl
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    container_name: tax-calculator-postgres

  api:
    build: ./
    ports: 
      - "9090:9090"
    network_mode: "host"
    depends_on: 
      - postgres
    environment: 
      POSTGRES_DB: postgres
      DB_CONNECTION_STRING: postgres://postgres@localhost:5432/user?sslmode=disable
    container_name: tax-calculator-api